name: usak_olay
description: Uşak Olay Flutter uygulaması
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  onesignal_flutter: ^5.3.3
  url_launcher: ^6.3.0
  share_plus: ^10.0.2

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#E9E9E9"
